server:
  port: 8082

spring:
  application:
    name: catalog-service
  profiles:
    active: local # switch to dev for TiDB Cloud
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

pixelmart:
  internal:
    allowed-service: order-service
  order:
    base-url: ${ORDER_SERVICE_URL:http://localhost:8083}
    internal-service-name: catalog-service
  auth:
    base-url: ${AUTH_SERVICE_URL:http://localhost:8081}
    internal-service-name: catalog-service
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      base-path: ${STORAGE_LOCAL_PATH:./data/uploads}
    s3:
      region: ${AWS_REGION:us-east-1}
      bucket: ${AWS_S3_BUCKET:}
      prefix: ${AWS_S3_PREFIX:pixelmart}

management:
  endpoints:
    web:
      exposure:
        include: health,info
